name: Autograding

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run GoogleTest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ googletest

      - name: Build tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ./test_triangulo
